spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
        - id: movies-service
          uri: lb://MOVIES-SERVICE
          predicates:
            - Path=/api/movies/**
          filters:
            - StripPrefix=2
  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8080/realms/DigitalMedia
        registration:
          api-gateway:
            provider: keycloak-provider
            client-id: api-gateway
            client-secret: BAuV8cFPeQ4VGAoKLznySmgv6yJfU5gN
            authorization-grant-type: authorization_code
            redirect-uri: 'http://localhost:9090/login/oauth2/code/keycloak'

server:
  port: 9090
logging:
  level:
    org:
      springframework:
        security: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
