spring:
  application:
    name: movies-service
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: 'create'
  data:
    mongodb:
      uri: mongodb://localhost:27017/moviesdb
  main:
    allow-circular-references: true
  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8080/realms/DigitalMedia
        registration:
          movie-service:
            provider: keycloak-provider
            client-id: microservicios
            client-secret: bIWYQuLcQpYIY0bI3J8klGnjFIyrrxZx
            authorization-grant-type: authorization_code
            redirect-uri: 'http://localhost:9090/login/oauth2/code/keycloak'

app:
  cors:
    allowed-origins: http://localhost:3000

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC
    disable-swagger-default-url: true
server:
  port: 9085
logging:
  level:
    org:
      springframework:
        security: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
